## This would be applying RL without clustring

In [6]:
import pandas as pd
import numpy as np
import os

import gymnasium as gym
from gym import Env
from gym import spaces

from enum import Enum

from stable_baselines3 import PPO

In [3]:
# spaces.Box(low = 0, high = 1).sample()

array([0.83460546], dtype=float32)

In [2]:
#get path of the curr project
print(os.getcwd())

C:\Users\AbdulRahman\Desktop\gradproj\Grad-Project\Implementation\AI\Agent


In [8]:
df = pd.read_csv("C:/Users/AbdulRahman/Desktop/gradproj/Grad-Project/Implementation/AI/DataSet/lateset Dataset Main/pre_processed_df_without.csv")

In [4]:
print((set(list(df['attributes_RestaurantsPriceRange2']))))

{1, 2, 3, 4}


In [5]:
print((set(list(df['stars']))))

{5.0, 3.5, 4.0, 4.5}


In [6]:
df.columns

Index(['latitude', 'longitude', 'stars', 'review_count',
       'attributes_RestaurantsPriceRange2', 'attributes_GoodForKids',
       'attributes_Ambience_touristy', 'attributes_Ambience_romantic',
       'attributes_Ambience_intimate', 'attributes_Ambience_trendy',
       'attributes_Ambience_classy', 'attributes_Ambience_casual',
       'Bars_Night', 'Beauty_Health_Care', 'Cafes', 'GYM',
       'Restaurants_Cuisines', 'Shops'],
      dtype='object')

In [7]:
df.head()

latitude  longitude  stars  review_count  \
0  39.955505 -75.155564    4.0            80   
1  39.953949 -75.143226    4.0           245   
2  39.943223 -75.162568    4.5           205   
3  40.006707 -75.289671    3.5           109   
4  39.962582 -75.135657    3.5            65   

   attributes_RestaurantsPriceRange2  attributes_GoodForKids  \
0                                  1                       1   
1                                  2                       0   
2                                  1                       1   
3                                  1                       1   
4                                  2                       1   

   attributes_Ambience_touristy  attributes_Ambience_romantic  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   attributes_Ambience_intimate  attributes_Ambience_trendy  \
0                             0                           0   
1                             0                           0   
2                             0                           0   
3                             0                           0   
4                             0                           0   

   attributes_Ambience_classy  attributes_Ambience_casual  Bars_Night  \
0                           0                           1           0   
1                           1                           0           0   
2                           0                           1           0   
3                           0                           1           0   
4                           1                           0           0   

   Beauty_Health_Care  Cafes  GYM  Restaurants_Cuisines  Shops  
0                   0      1    0                     1      0  
1                   0      0    0                     1      0  
2                   0      0    0                     1      0  
3                   0      0    0                     1      0  
4                   0      0    0                     1      0

In [23]:
# Box(low=0, high=5, shape=(20,), dtype=np.float32).sample()

array([1.6066295 , 2.4351947 , 1.4334623 , 3.050269  , 3.3055985 ,
       1.458249  , 0.28778958, 0.72118527, 0.3882745 , 3.296755  ,
       0.53379095, 2.2658453 , 0.48177618, 4.4178843 , 4.453072  ,
       2.4207904 , 0.75164735, 0.08341315, 3.6692133 , 2.5314713 ],
      dtype=float32)

In [4]:
spaces.Box(low = 0, high = 1).sample()

array([0.7398428], dtype=float32)

# mapping user pref text to vector

In [ ]:
lst = ['Bars_Night','Beauty_Health_Care','Cafes','GYM','Restaurants_Cuisines','Shops',
'romantic', 'intimate', 'family_friendly', 'star', 'price_range','trendy','classy','touristy', 'casual']

user_pref = [0]*len(lst)

print(user_pref)
# len(user_pref)

mp = {}
for i in range(len(lst)):
  mp[lst[i]] = i

for x in mp.items():
  print(x)

In [ ]:
class preferences:
  def __init__(self, category : str,
               star : float,
               days: int,
               price_range: int,
               trendy : bool,
               classy : bool,
               touristy : bool,
               casual : bool,
               family_friendly_or_romantic: str):
    self.category = category
    self.star = star
    self.days = days
    self.price_range = price_range
    self.trendy = trendy
    self.classy = classy
    self.touristy = touristy
    self.casual = casual
    self.family_friendly_or_romantic = family_friendly_or_romantic

In [ ]:
def fill(pref : preferences):
  user_pref[mp[pref.category]] = 1
  user_pref[mp['star']] = pref.star
  user_pref[mp['price_range']] = pref.price_range
  user_pref[mp['trendy']] = 0 if pref.trendy == False else 1
  user_pref[mp['classy']] = 0 if pref.classy == False else 1
  user_pref[mp['touristy']] = 0 if pref.touristy == False else 1
  user_pref[mp['casual']] = 0 if pref.casual == False else 1
  user_pref[mp[pref.family_friendly_or_romantic]] = 1

In [ ]:
def get_mapping(user_pref, lst):
  for i in range(0,len(lst)):
    print(lst[i], user_pref[i])

In [ ]:
user_pref = [0]*len(lst)
pref = preferences('Restaurants_Cuisines', 3.5, 3, 2, True, False, False, False, 'family_friendly')
fill(pref)

In [ ]:
get_mapping(user_pref, lst)

# Building the enviroment 

In [42]:
# class Travia_Env(Env):
#     def __init__(self):
#         business_space = spaces.Dict({
#             "stars": spaces.Box(low=0, high=5, shape=(1,), dtype=np.float32),
#             "price_range": spaces.Discrete(5),
#             "attributes_GoodForKids": spaces.Discrete(2),
#             "attributes_Ambience_romantic": spaces.Discrete(2),
#             "attributes_Ambience_intimate": spaces.Discrete(2),
#             "attributes_Ambience_trendy": spaces.Discrete(2),
#             "attributes_Ambience_classy": spaces.Discrete(2),
#             "attributes_Ambience_casual": spaces.Discrete(2),
#             "Bars_Night": spaces.Discrete(2),
#             "Beauty_Health_Care": spaces.Discrete(2),
#             "Cafes": spaces.Discrete(2),
#             "GYM": spaces.Discrete(2),
#             "Restaurants_Cuisines": spaces.Discrete(2),
#             "Shops": spaces.Discrete(2),
#         })
#         self.observation_space = spaces.Dict({
#             "user_pref": spaces.Dict({
#                     "Bars_Night": spaces.Discrete(2),
#                     "Beauty_Health_Care": spaces.Discrete(2),
#                     "Cafes": spaces.Discrete(2),
#                     "GYM": spaces.Discrete(2),
#                     "Restaurants_Cuisines": spaces.Discrete(2),
#                     "Shops": spaces.Discrete(2),
#                     "attributes_Ambience_romantic": spaces.Discrete(2),
#                     "attributes_Ambience_intimate": spaces.Discrete(2),
#                     "attributes_GoodForKids": spaces.Discrete(2),
#                     "star": spaces.Box(low=0, high=5, shape=(1,), dtype=np.float32),
#                     "price_range": spaces.Discrete(5),
#                     "trendy": spaces.Discrete(2),
#                     "classy": spaces.Discrete(2),
#                     "touristy": spaces.Discrete(2),
#                     "casual": spaces.Discrete(2),
#                 }),
#             "business_data": spaces.Sequence(business_space)
#         })
#         self.action_space = spaces.Box(low=0, high=1, shape=(1,15), dtype=np.float32)
#     def render(self):
#         pass
#     def step(self, action):
#         pass
#     def reset(self):
#         pass

In [47]:
from gym import Env
from gym.spaces import Dict, Box, Discrete, Sequence
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

class Travia_Env(Env):
    def __init__(self, dataset_path, k_days):
        # Load the dataset
        self.df = pd.read_csv(dataset_path)
        self.k_days = k_days

        # Define features used for cosine similarity
        self.feature_cols = [
            "stars",
            "attributes_RestaurantsPriceRange2",
            "attributes_GoodForKids",
            "attributes_Ambience_touristy",
            "attributes_Ambience_romantic",
            "attributes_Ambience_intimate",
            "attributes_Ambience_trendy",
            "attributes_Ambience_classy",
            "attributes_Ambience_casual"
        ]
        self.num_features = len(self.feature_cols)  # 9 features

        # Category columns for filtering
        self.category_cols = [
            "Bars_Night", "Beauty_Health_Care", "Cafes", "GYM",
            "Restaurants_Cuisines", "Shops"
        ]

        # Define business space (subset of dataset columns)
        business_space = spaces.Dict({
            "stars": spaces.Box(low=0, high=5, shape=(1,), dtype=np.float32),
            "attributes_RestaurantsPriceRange2": spaces.Discrete(5),  # 0-4 (0 if missing)
            "attributes_GoodForKids": spaces.Discrete(2),
            "attributes_Ambience_touristy": spaces.Discrete(2),
            "attributes_Ambience_romantic": spaces.Discrete(2),
            "attributes_Ambience_intimate": spaces.Discrete(2),
            "attributes_Ambience_trendy": spaces.Discrete(2),
            "attributes_Ambience_classy": spaces.Discrete(2),
            "attributes_Ambience_casual": spaces.Discrete(2),
            "Bars_Night": spaces.Discrete(2),
            "Beauty_Health_Care": spaces.Discrete(2),
            "Cafes": spaces.Discrete(2),
            "GYM": spaces.Discrete(2),
            "Restaurants_Cuisines": spaces.Discrete(2),
            "Shops": spaces.Discrete(2),
        })

        # Observation space
        self.observation_space = spaces.Dict({
            "user_pref": spaces.Dict({
                "category": spaces.Discrete(6),  # Index of category_cols
                "min_stars": spaces.Discrete(5, start=1),  # 1-5
                "price_range": spaces.Discrete(4, start=1),  # 1-4
                "ambience": spaces.Discrete(4),  # 0: touristy, 1: trendy, 2: classy, 3: casual
                "intimate_or_family": spaces.Discrete(3)  # 0: romantic, 1: intimate, 2: GoodForKids
            }),
            "business_data": spaces.Sequence(business_space),
        })

        # Action space: Weight vector for features (0 to 1)
        self.action_space = spaces.Box(
            low=0.0,
            high=1.0,
            shape=(self.num_features,),  # One weight per feature
            dtype=np.float32
        )

    def _business_to_vector(self, business):
        """Convert a business dict to a vector for cosine similarity."""
        return np.array([
            business["stars"][0],
            business["attributes_RestaurantsPriceRange2"],
            business["attributes_GoodForKids"],
            business["attributes_Ambience_touristy"],
            business["attributes_Ambience_romantic"],
            business["attributes_Ambience_intimate"],
            business["attributes_Ambience_trendy"],
            business["attributes_Ambience_classy"],
            business["attributes_Ambience_casual"]
        ], dtype=np.float32)

    def _pref_to_target_vector(self):
        """Convert user preferences to a target vector for reward calculation."""
        target = np.zeros(self.num_features, dtype=np.float32)
        target[0] = self.user_pref["min_stars"]  # stars
        target[1] = self.user_pref["price_range"]  # price range
        if self.user_pref["category"] in [2, 4]:  # Cafes or Restaurants_Cuisines
            if self.user_pref["intimate_or_family"] == 0:  # romantic
                target[4] = 1.0
            elif self.user_pref["intimate_or_family"] == 1:  # intimate
                target[5] = 1.0
            elif self.user_pref["intimate_or_family"] == 2:  # GoodForKids
                target[2] = 1.0
        ambience_idx = {
            0: 3,  # touristy
            1: 6,  # trendy
            2: 7,  # classy
            3: 8   # casual
        }[self.user_pref["ambience"]]
        target[ambience_idx] = 1.0
        return target

    def reset(self, user_pref):
        """Reset the environment with new user preferences."""
        self.user_pref = user_pref
        category_idx = user_pref["category"]
        category = self.category_cols[category_idx]
        min_stars = user_pref["min_stars"]

        # Filter businesses by category and min stars
        filtered_df = self.df[
            (self.df[category] == 1) & (self.df["stars"] >= min_stars)
        ].fillna(0)  # Replace NaN with 0 for missing attributes
        self.businesses = [row.to_dict() for _, row in filtered_df.iterrows()]
        return self._get_obs()

    def step(self, action):
        """Take a step: generate weights, score businesses, select top k_days."""
        weights = action.reshape(1, -1)  # Shape: (1, num_features)

        # Convert businesses to vectors
        business_vectors = np.array([self._business_to_vector(b) for b in self.businesses])

        # Compute cosine similarity
        scores = cosine_similarity(weights, business_vectors).flatten()

        # Select top k_days businesses
        top_k_indices = np.argsort(scores)[-self.k_days:]
        selected_businesses = [self.businesses[i] for i in top_k_indices]

        # Compute reward
        reward = self._compute_reward(selected_businesses)

        # Done after one step
        done = True
        info = {"selected_businesses": selected_businesses, "scores": scores[top_k_indices]}
        return self._get_obs(), reward, done, info

    def _get_obs(self):
        return {
            "user_pref": self.user_pref,
            "business_data": self.businesses
        }

    def _compute_reward(self, selected_businesses):
        """Reward based on how well selections match user preferences."""
        target_vector = self._pref_to_target_vector().reshape(1, -1)
        selected_vectors = np.array([self._business_to_vector(b) for b in selected_businesses])
        similarities = cosine_similarity(target_vector, selected_vectors).flatten()
        return np.mean(similarities)

In [49]:
path = "C:/Users/AbdulRahman/Desktop/gradproj/Grad-Project/Implementation/AI/DataSet/lateset Dataset Main/pre_processed_df_without.csv"     
env = Travia_Env(path,3) 

In [54]:
env.observation_space.sample()

OrderedDict([('business_data',
              (OrderedDict([('Bars_Night', 1),
                            ('Beauty_Health_Care', 1),
                            ('Cafes', 0),
                            ('GYM', 0),
                            ('Restaurants_Cuisines', 0),
                            ('Shops', 1),
                            ('attributes_Ambience_casual', 0),
                            ('attributes_Ambience_classy', 0),
                            ('attributes_Ambience_intimate', 0),
                            ('attributes_Ambience_romantic', 0),
                            ('attributes_Ambience_touristy', 1),
                            ('attributes_Ambience_trendy', 1),
                            ('attributes_GoodForKids', 1),
                            ('attributes_RestaurantsPriceRange2', 4),
                            ('stars', array([3.8269427], dtype=float32))]),
               OrderedDict([('Bars_Night', 1),
                            ('Beauty_Health_Care',

In [55]:
env.action_space.sample()

array([0.4452875 , 0.1437275 , 0.28770465, 0.90674895, 0.5641847 ,
       0.37494993, 0.01858635, 0.36591086, 0.918976  ], dtype=float32)

C:\Users\AbdulRahman\AppData\Roaming\Python\Python313\site-packages\stable_baselines3\common\env_checker.py:462: UserWarning: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) cf. https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  warnings.warn(


Using cuda device


C:\Users\AbdulRahman\AppData\Roaming\Python\Python313\site-packages\stable_baselines3\common\on_policy_algorithm.py:150: UserWarning: You are trying to run PPO on the GPU, but it is primarily intended to run on the CPU when not using a CNN policy (you are using ActorCriticPolicy which should be a MlpPolicy). See https://github.com/DLR-RM/stable-baselines3/issues/1245 for more info. You can pass `device='cpu'` or `export CUDA_VISIBLE_DEVICES=` to force using the CPU.Note: The model will train, but the GPU utilization will be poor and the training might take longer than on CPU.
  warnings.warn(


-----------------------------
| time/              |      |
|    fps             | 8    |
|    iterations      | 1    |
|    time_elapsed    | 228  |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 8           |
|    iterations           | 2           |
|    time_elapsed         | 466         |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.019075137 |
|    clip_fraction        | 0.235       |
|    clip_range           | 0.2         |
|    entropy_loss         | -12.7       |
|    explained_variance   | -3.05       |
|    learning_rate        | 0.0003      |
|    loss                 | -0.0469     |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0242     |
|    std                  | 0.994       |
|    value_loss           | 0.0308      |
----------------------------------

TypeError: ObservationWrapper.reset() got an unexpected keyword argument 'user_pref'

In [65]:
def evaluate_model(model, env, user_pref, n_episodes=5):
    env = FlattenObservation(env)
    rewards = []
    for _ in range(n_episodes):
        obs, _ = env.reset(user_pref=user_pref)
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, done, truncated, info = env.step(action)
        rewards.append(reward)
        print(f"Selected businesses: {[b['name'] for b in info['selected_businesses']]}")
        print(f"Reward: {reward}")
    print(f"Average reward over {n_episodes} episodes: {np.mean(rewards)}")

In [67]:
user_pref = {
        "category": 2,  # Cafes
        "min_stars": 4,  # 4+ stars
        "price_range": 2,  # $$
        "ambience": 3,  # casual
        "intimate_or_family": 2  # GoodForKids
    }
eval_env = Travia_Env(dataset_path, k_days)
evaluate_model(model, eval_env, user_pref)

TypeError: ObservationWrapper.reset() got an unexpected keyword argument 'user_pref'